package money.open.cards.visabase.constants;

public enum  TPEResponseCode{
	APPROVED_OR_COMPLETED("00"),
	REFER_TO_CARD_ISSUER("01"),
	INVALID_MERCHANT("03"),
	CAPTURE_CARD("04"),
	DO_NOT_HONOR("05"),
	ERROR("06"),
	HONOR_WITH_ID_APPROVAL("08"),
	PARTIAL_APPROVAL("10"),
	INVALID_TRANSACTION("12"),
	INVALID_AMOUNT("13"),
	INVALID_CARD_OR_ACCOUNT_NUMBER("14"),
	INVALID_ISSUER("15"),
	FORMAT_ERROR("30"),
	LOST_CARD("41"),
	STOLEN_CARD("43"),
	INSUFFICEINT_BALANCE_OR_OVER_CREDIT_LIMIT("51"),
	EXPIRED_CARD("54"),
	INVALIDA_PIN("55"),
	TRANSACTION_NOT_PERMITTED("57"),
	TRANSACTION_NOT_PERMITTED_TO_TERMINAL("58"),
	EXCEED_WITHDRAWL_LIMIT("61"),// Daily Transaction Limit
	//EXCEED_LIMIT("61"),// Max card limit
	EXCEED_LIMIT("28"),// Max card Limit
	RESTRICTED_CARD("62"),
	SECURITY_VIOLATION("63"),
	EXCEED_WITHDRAWL_COUNT_LIMIT("65"),// Daily Transaction Count
	CONTACT_CARD_ISSUER("70"),
	PIN_NOT_CHANGED("71"),
	PIN_TRY_LIMIT_EXCEEDS("75"),
	INVALID_TO_ACCOUNT_SPEICIFIED("76"),
	INVALID_FROM_ACCOUNT_SPECIFIED("77"),
	INVALID_ACCOUNT_SPECIFIED("78"),
	DOMESTIC_DEBIT_TRANSACTION_NOT_ALLOWED("81"),
	BENEFICIARY_LIMIT_REACHED("82"),
	BENEFICIARY_LIMIT_HOLD_REACHED("83"),
	INVALID_AUTHORIZATION_LIFE_CYCLE("84"),
	NOT_DECLINED("85"),
	PIN_VALIDATION_NOTPOSSIBLE("86"),
	PURCHASE_AMOUNT_ONLY("87"),
	CRYPTOGRAPHIC_FEATURE("88"),
	UNACCEPTABLE_PIN_TRANSACTION_DECLINED("89"),
	ISSUER_SYSTEM_INOPERATIVE("91"),	
	UNABLE_TO_ROUTE_TRANSACTION("92"),
	DUPLICATE_TRANSMNSSION_DETECTED("94"),
	SYSTEM_ERROR("96"),
	LoyaltyFailed("93"),
	NoRedeemPoints("16"),
	
	// Added BY Balachandrasekhar for specific response code
	
	EXCEED_MONTHLY_WITHDRAWL_LIMIT("17"),
	EXCEED_MONTHLY_WITHDRAWL_COUNTLIMIT("18"),
	EXCEED_YEARLY_WITHDRAWL_LIMIT("19"),
	EXCEED_YEARLY_WITHDRAWL_COUNTLIMIT("20"),
	EXCEED_WEEKLY_WITHDRAWL_LIMIT("21"),
	EXCEED_WEEKLY_WITHDRAWL_COUNTLIMIT("22"),
	BELOW_MINIMUM_AMOUNT("23"),
	EXCEED_MAXIMUM_AMOUNT("24"),
	EXCEED_MAXIMUM_AMOUNT_POSTILION("61"),
	EXCEED_WEEKLY_BENIFICIARY_LIMIT("25"),
	EXCEED_MONTHLY_BENIFICIARY_LIMIT("26"),
	EXCEED_YEARLY_BENIFICIARY_LIMIT("27"),
	CITRUS_FAILURE_ADDMONEY("29"),
			
	INVALID_CHECKING_ACCOUNT("52"),	
	INVALID_CREDIT_ACCOUNT("39"),
	INVALID_CREDIT_ACCOUNT_POS("T8"),
	INVALID_SAVINGS_ACCOUNT("52"),
	ARQC_VERIFICATION_FAILURE("E3"),
	ARQC_VERIFICATION_FAILURE_MERCURY("88"),
	TVR_VERIFICATION_FAILURE("E4"),
	CVR_VERIFICATION_FAILURE("E5"),
	CUTOVER_RECONDATE_INSERTION_FAILURE("11"),
	PARTITIAL_REVERSAL("32")
	;

	
	
	public String responseCode;

	public String getResponseCode()
	{
		return responseCode;
	}

	public void setResponseCode(String responseCode)
	{
		this.responseCode = responseCode;
	}
	
	TPEResponseCode(String responseCode)
	{
		this.responseCode=responseCode;
	}
	
}
